### ISSUE TITLE
Get 'attempt to multiply with overflow' error with ONNX file

### ISSUE THREAD

**Issue by psiphi75** [snipsco/tract#163]
Hi, I'm using tract on another onnx file and get the following error when I try to optimise the file: 

```text
thread 'main' panicked at 'attempt to multiply with overflow', /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/arith.rs:801:51
```

The offending onnx file can be [found here](https://psiphi75.github.io/workingfiles/onnx.onnx).

The code to run this is:

```Rust
use std::path::Path;
use tract_core::prelude::*;

fn main() -> TractResult<()> {
  // load the model
  println!("Load Onnx");
  let path = Path::new("onnx.onnx");
  let mut model = tract_onnx::onnx().model_for_path(path)?;

  // specify input type and shape
  println!("Specify input shape");
  model.set_input_fact(0, TensorFact::dt_shape(f32::datum_type(), tvec!(1, 3, 64, 64)))?;

  // optimize the model and get an execution plan
  println!("Optimising model");
  model.into_optimized()?;
}
```

The full stacktrace is:

```text
thread 'main' panicked at 'attempt to multiply with overflow', /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/arith.rs:801:51
stack backtrace:
   0:     0x5603dbe82afb - backtrace::backtrace::libunwind::trace::hfe5db90796807973
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x5603dbe82afb - backtrace::backtrace::trace_unsynchronized::h34b865a835594335
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x5603dbe82afb - std::sys_common::backtrace::_print::h527254ae44989167
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5603dbe82afb - std::sys_common::backtrace::print::he85dd5ddddf46503
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5603dbe82afb - std::panicking::default_hook::{{closure}}::h847a2eb38b396f14
                               at src/libstd/panicking.rs:200
   5:     0x5603dbe827d7 - std::panicking::default_hook::h2ca0f9a30a0e206b
                               at src/libstd/panicking.rs:214
   6:     0x5603dbe83210 - std::panicking::rust_panic_with_hook::hffcefc09751839d1
                               at src/libstd/panicking.rs:477
   7:     0x5603dbe82d92 - std::panicking::continue_panic_fmt::hc0f142c930c846fc
                               at src/libstd/panicking.rs:384
   8:     0x5603dbe82c76 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x5603dbe9c0dd - core::panicking::panic_fmt::h2daf88b2616ca2b2
                               at src/libcore/panicking.rs:85
  10:     0x5603dbe9c01c - core::panicking::panic::h2d0bc53a963fb996
                               at src/libcore/panicking.rs:49
  11:     0x5603db383f9b - <usize as core::ops::arith::MulAssign>::mul_assign::h0ddb15e88dbf93db
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/arith.rs:801
  12:     0x5603db384920 - <usize as core::ops::arith::MulAssign<&usize>>::mul_assign::h0b18b310cf23d13e
                               at core/src/lib.rs:1
  13:     0x5603db309b67 - tract_core::ops::math::mat_mul::Geo<T>::new::{{closure}}::hc7f57c849900bf73
                               at core/src/ops/math/mat_mul.rs:164
  14:     0x5603db573e86 - <core::iter::adapters::Scan<I,St,F> as core::iter::traits::iterator::Iterator>::next::{{closure}}::hd1c234b5a37658fb
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/adapters/mod.rs:1679
  15:     0x5603dbc81c6a - core::option::Option<T>::and_then::h6268d3a9d77a59ce
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/option.rs:624
  16:     0x5603db573cb3 - <core::iter::adapters::Scan<I,St,F> as core::iter::traits::iterator::Iterator>::next::h90da42eaf54874b1
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/adapters/mod.rs:1679
  17:     0x5603db5b6c27 - <&mut I as core::iter::traits::iterator::Iterator>::next::h08211bfabbef9568
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:2608
  18:     0x5603db580c82 - core::iter::traits::iterator::Iterator::nth::hd4d628382565a50e
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:315
  19:     0x5603db5b7fd3 - <core::iter::adapters::Skip<I> as core::iter::traits::iterator::Iterator>::next::hd50a102c4cb55bba
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/adapters/mod.rs:1420
  20:     0x5603daef0cb0 - <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend::h76ba7fea8679899f
                               at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.6.10/lib.rs:1357
  21:     0x5603daf62420 - <smallvec::SmallVec<A> as core::iter::traits::collect::FromIterator<<A as smallvec::Array>::Item>>::from_iter::hd0f92089e463168a
                               at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.6.10/lib.rs:1342
  22:     0x5603db58ebc9 - core::iter::traits::iterator::Iterator::collect::hbf1b5f20172114bc
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/iter/traits/iterator.rs:1466
  23:     0x5603db3081c4 - tract_core::ops::math::mat_mul::Geo<T>::new::h275a6d2cbacf74f9
                               at core/src/ops/math/mat_mul.rs:159
  24:     0x5603db30b0ab - tract_core::ops::math::mat_mul::new_mat_mul_unary_finite::hea080a512d4010f0
                               at core/src/ops/math/mat_mul.rs:463
  25:     0x5603db8e5c83 - <tract_core::ops::math::mat_mul::MatMulUnary as tract_core::ops::Op>::codegen::h0b79d28b91e22295
                               at core/src/ops/math/mat_mul.rs:364
  26:     0x5603dbb7cb3f - <tract_core::optim::CodegenOps as tract_core::optim::TypedPass>::pass::hc6771f429b5f96d3
                               at core/src/optim/mod.rs:117
  27:     0x5603db8f6c03 - tract_core::model::<impl tract_core::model::model::ModelImpl<tract_core::model::tensor_info::TypedTensorInfo,alloc::boxed::Box<dyn tract_core::ops::TypedOp>>>::codegen::ha4b582fc098ece07
                               at core/src/model/mod.rs:294
  28:     0x5603db8f4f83 - tract_core::model::<impl tract_core::model::model::ModelImpl<tract_core::analyser::types::TensorFact,alloc::boxed::Box<dyn tract_core::ops::InferenceOp>>>::into_optimized::hbe0fc2f2165b33ca
                               at core/src/model/mod.rs:260
  29:     0x5603da7d2016 - onnx_gru_example::main::h9bc5e9b63b97e7a6
                               at examples/onnx-gru/src/main.rs:17
  30:     0x5603da7d1852 - std::rt::lang_start::{{closure}}::hc92a5ddd759a31b1
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  31:     0x5603dbe82c13 - std::rt::lang_start_internal::{{closure}}::h447d8812e3ee306d
                               at src/libstd/rt.rs:49
  32:     0x5603dbe82c13 - std::panicking::try::do_call::h4a61cb372364c745
                               at src/libstd/panicking.rs:296
  33:     0x5603dbe84d5a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:82
  34:     0x5603dbe8371d - std::panicking::try::hdf71f938885bca42
                               at src/libstd/panicking.rs:275
  35:     0x5603dbe8371d - std::panic::catch_unwind::h7e85dbf162b1611a
                               at src/libstd/panic.rs:394
  36:     0x5603dbe8371d - std::rt::lang_start_internal::h1e06cc26b9fc25ea
                               at src/libstd/rt.rs:48
  37:     0x5603da7d1819 - std::rt::lang_start::ha4cdda85009acf6c
                               at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  38:     0x5603da7d255a - main
  39:     0x7f42ed82db6b - __libc_start_main
  40:     0x5603da7cf18a - _start
  41:                0x0 - <unknown>
```

**Comment by kali** [comment]
`cargo run onnx.onnx -i 1x3x64x64xf32 --proto dump`

```
8 MaxPool 14
  * input fact  #0: 7/0> 1x50x26x26xF32
  * output fact #0: 1x50x13x13xF32 >9/0
  * Attr kernel_shape: name: "kernel_shape" type: INTS ints: 2 ints: 2
    Attr pads: name: "pads" type: INTS ints: 0 ints: 0 ints: 0 ints: 0
    Attr strides: name: "strides" type: INTS ints: 2 ints: 2
9 IntoShape 16
  * input fact  #0: 8/0> 1x50x13x13xF32
  * output fact #0: -1x8450xF32 >10/0
  * to shape: 18446744073709551615x8450
10 MatMulUnary 17-ab
  * input fact  #0: 9/0> -1x8450xF32
  * output fact #0: -1x500xF32 >11/0
  * a_trans:false b_trans:true c_trans:true
  * A: 500x8450xF32 0.0005942462, -0.004034171, -0.010062962, 0.008186151, -0.0033822584, -0.0030546563, 0.0012139356, 0.0064912643...
```

Lol. One more of these terrible magic -1 value. Will fix right away :)

**Comment by kali** [comment]
fix is on master, i will probably do a release later this week.

**Comment by psiphi75** [comment]
Thanks for the quick fix.  I've tested it and it works.

**Comment by kali** [comment]
0.5.0 is out :)

**Comment by psiphi75** [comment]
Thanks.  I've tested it and it works :)
