### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by rth** [snipsco/tract#57]
I tried to build the latest dev version of the project with rustc 1.31.0, with,
```
cargo build
```

but I'm getting the following error,
```
[...]
   Compiling jpeg-decoder v0.1.15                                                                                                              
   Compiling tract-core v0.2.6-pre (/home/rth/src/tract/core)                                                                                  
   Compiling failure v0.1.5                                                                                                                    
   Compiling image v0.19.0                                                                                                                     
   Compiling mio_httpc v0.6.24
   Compiling tract-onnx v0.2.6-pre (/home/rth/src/tract/onnx)                                                                                  
error: failed to run custom build command for `tract-onnx v0.2.6-pre (/home/rth/src/tract/onnx)`                                               
process didn't exit successfully: `/home/rth/src/tract/target/debug/build/tract-onnx-f9bfe0fb1264b616/build-script-build` (exit code: 101)
--- stdout
DEBUG ensure_onnx_git_checkout 1
DEBUG ensure_onnx_git_checkout 2
DEBUG ensure_onnx_git_checkout 3
DEBUG ensure_onnx_git_checkout 4
DEBUG ensure_onnx_git_checkout 5

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 18, kind: Other, message: "Invalid cross-device link" }', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
````

Am I missing something?

**Comment by kali** [comment]
That's interesting... it should not happen, `cargo build` is supposed to work.

I think I may know what is happening... Is your "tmp" directory located on a different filesystem than the one you try to build tract in ?

**Comment by rth** [comment]
> Is your "tmp" directory located on a different filesystem than the one you try to build tract in ?

Yes, it's a tmpfs..

**Comment by kali** [comment]
@rth Care to give this fix a try ? travis will not teach us very much in that case

**Comment by rth** [comment]
When using the `issue-57` branch, the previous issue does go away but I get new one :)

```
$ cargo build  
[...]                                                                         
   Compiling jpeg-decoder v0.1.15                                                                                                              
   Compiling mio_httpc v0.6.24                                                                                                                 
   Compiling image v0.19.0                                                                                                                     
   Compiling tract-onnx v0.2.6-pre (/home/rth/src/tract/onnx)                                                                                  
error: failed to run custom build command for `tract-onnx v0.2.6-pre (/home/rth/src/tract/onnx)`                                               
process didn't exit successfully: `/home/rth/src/tract/target/debug/build/tract-onnx-7c96f46c03aa597d/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'assertion failed: node_tests.exists()', onnx/build.rs:31:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
it looks like https://github.com/snipsco/tract/blob/822e4b5e6957fa4a299e629d3e28692cef82ae64/onnx/build.rs#L37 path does not exist? I tried running `cargo clean` then re-compile everything from scratch but it didn't help.

**Comment by kali** [comment]
Can you try and remove the .onnx dir form tract/onnx ? It may help for now... i’ll try a more robust approach tomorrow morning.

**Comment by rth** [comment]
> Can you try and remove the .onnx dir form tract/onnx ?

Yes, I can confirm that allowed to have a successful build.
